version: "3.9"

networks:
        tcynthia.42.fr:
                name: ${NETWORK}

services:
        nginx:
                depends_on:
                        - wordpress
                domainname: ${NETWORK}
                hostname: ${NETWORK}
                container_name: nginx
                build: ./nginx
                volumes:
                        - wordpress:/var/www/wordpress
                networks:
                        - ${NETWORK}
                ports:
                        - "443:443"
                deploy:
                        restart_policy:
                                condition: on-failure
                                delay: 5s
                                max-attempts: 3
        wordpress:
                depends_on:
                        - mariadb
                container_name: wordpress
                build: ./wordpress
                volumes:
                        - wordpress:/var/www/wordpress
                networks:
                        - ${NETWORK}
                environment:
                        COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
                        DB_HOST: ${DB_HOST}
                        DB_NAME: ${DB_NAME}
                        DB_USER: ${DB_USER}
                        DB_PASSWORD: ${DB_PASSWORD}
                deploy:
                        restart_policy:
                                condition: on-failure
                                delay: 5s
                                max-attempts: 3
        mariadb:  
                container_name: ${DB_HOST}
                build: ./mariadb
                volumes:
                        - mariadb:/var/lib/mysql
                networks:
                        - ${NETWORK}
                environment:
                        DB_NAME: ${DB_NAME}
                        DB_USER: ${DB_USER}
                        DB_PASSWORD: ${DB_PASSWORD}
                deploy:
                        restart_policy:
                                condition: on-failure
                                delay: 5s
                                max-attempts: 3
volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/${USERNAME}/data/wordpress
                        o: bind
                        type: none
        mariadb:
                name: ${DB_HOST}
                driver: local
                driver_opts:
                        device: /home/${USERNAME}/data/mariadb
                        o: bind
                        type: none
