version: "3.9"

networks:
        inception:
                name: ${NETWORK}

services:
        mariadb:  
                container_name: mariadb
                build: ./requirements/mariadb
                volumes:
                        - mariadb:/var/lib/mysql
                networks:
                        - ${NETWORK}
                restart: always
                env_file:
                        - .env
        wordpress:
                container_name: wordpress
                depends_on:
                        - mariadb
                build: ./requirements/wordpress
                volumes:
                        - wordpress:/var/www/html
                networks:
                        - ${NETWORK}
                restart: always
                env_file:
                        - .env
        nginx:
                container_name: nginx
                depends_on:
                        - wordpress
                build: ./requirements/nginx
                volumes:
                        - wordpress:/var/www/html
                networks:
                        - ${NETWORK}
                ports:
                        - "443:443"
                restart: always
                env_file:
                        - .env

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/tcynthia/data/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/tcynthia/data/mariadb
                        o: bind
                        type: none
