version: "3.9"

networks:
        net_inception:
                name: ${NETWORK}

services:
        nginx:
                depends_on:
                        - wordpress
                domainname: ${NETWORK}
                hostname: ${NETWORK}
                container_name: nginx
                build: ./nginx
                volumes:
                        - wordpress:/var/www/wordpress
                networks:
                        - ${NETWORK}
                ports:
                        - "443:443"
                deploy:
                        restart_policy:
                                condition: on-failure
                                delay: 5s
                env_file:
                  - .env
        wordpress:
                depends_on:
                        - mariadb
                container_name: wordpress
                build: ./wordpress
                volumes:
                        - wordpress:/var/www/wordpress
                networks:
                        - ${NETWORK}
                deploy:
                        restart_policy:
                                condition: on-failure
                                delay: 5s
                env_file:
                  - .env
        mariadb:  
                container_name: ${DB_HOST}
                build: ./mariadb
                volumes:
                        - mariadb:/var/lib/mysql
                networks:
                        - ${NETWORK}
                deploy:
                        restart_policy:
                                condition: on-failure
                                delay: 5s
                env_file:
                  - .env
volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        o: bind
                        type: none
                        device: /home/${USERNAME}/data/wordpress
        mariadb:
                name: ${DB_HOST}
                driver: local
                driver_opts:
                        o: bind
                        type: none
                        device: /home/${USERNAME}/data/mariadb
