version: "3.9"

networks:
        net_inception:
                name: ${NETWORK}

services:
        mariadb:  
                container_name: ${DB_HOST}
                build: ./mariadb
                image: ${DB_HOST}
                volumes:
                        - mariadb:/var/lib/mysql
                networks:
                        - ${NETWORK}
                restart: always
                env_file:
                        - .env
        wordpress:
                depends_on:
                        - mariadb
                container_name: wordpress
                build: ./wordpress
                image: wordpress
                volumes:
                        - wordpress:/var/www/wordpress
                networks:
                        - ${NETWORK}
                restart: always
                env_file:
                        - .env
        nginx:
                depends_on:
                        - wordpress
                domainname: ${NETWORK}
                hostname: ${NETWORK}
                container_name: nginx
                build: ./nginx
                image: nginx
                volumes:
                        - wordpress:/var/www/wordpress
                networks:
                        - ${NETWORK}
                ports:
                        - "443:443"
                restart: always
                env_file:
                        - .env

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/${USERNAME}/data/wordpress
                        o: bind
                        type: none
        mariadb:
                name: ${DB_HOST}
                driver: local
                driver_opts:
                        device: /home/${USERNAME}/data/mariadb
                        o: bind
                        type: none
