version: "3.9"
services:
  mysql:
    image: kdustin/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    networks:
      - host

  wordpress:
    image: kdustin/wordpress
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: wp_
    restart: always
    networks:
      - host

  nginx:
    image: kdustin/nginx
    volumes:
      - wordpress:/var/www/html
    ports:
      - 443:443
    restart: always
    networks:
      - host

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      device: '/home/kdustin/data/mariadb'
      o: 'bind'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      device: '/home/kdustin/data/wordpress'
      o: 'bind'

networks:
  host:
    name: host-network
    driver: bridge
