version: "3.9"

networks:
        net_inception:
                name: ${NETWORK}

services:
        mariadb:  
                container_name: ${DB_HOST}
                build: ./requirements/${DB_HOST}
                volumes:
                        - ${DB_HOST}:/var/lib/mysql
                networks:
                        - ${NETWORK}
                restart: always
                env_file:
                        - .env
        wordpress:
                container_name: wordpress
                depends_on:
                        - ${DB_HOST}
                build: ./requirements/wordpress
                volumes:
                        - wordpress:/var/www/html
                networks:
                        - ${NETWORK}
                restart: always
                env_file:
                        - .env
        nginx:
                container_name: nginx
                depends_on:
                        - wordpress
                build: ./requirements/nginx
                volumes:
                        - wordpress:/var/www/html
                networks:
                        - ${NETWORK}
                ports:
                        - "443:443"
                restart: always
                env_file:
                        - .env

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/${USERNAME}/data/wordpress
                        o: bind
                        type: none
        mariadb:
                name: ${DB_HOST}
                driver: local
                driver_opts:
                        device: /home/${USERNAME}/data/mariadb
                        o: bind
                        type: none
