version: "3.9"

networks:
        tcynthia.42.fr:
                name: ${NETWORK}

services:
        nginx:
                depends_on:
                        - wordpress
                domainname: ${NETWORK}
                hostname: ${NETWORK}
                container_name: nginx
                build: ./nginx
                image: nginx
                volumes:
                        - wordpress:/var/www/wordpress
                networks:
                        - ${NETWORK}
                ports:
                        - "443:443"
                restart: always
        wordpress:
                depends_on:
                        - mariadb
                container_name: wordpress
                build: ./wordpress
                image: wordpress
                volumes:
                        - wordpress:/var/www/wordpress
                networks:
                        - ${NETWORK}
                ports:
                        - "5221:9000"
                restart: always
                environment:
                        COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
                        DB_HOST: ${DB_HOST}
                        DB_NAME: ${DB_NAME}
                        DB_USER: ${DB_USER}
                        DB_PASSWORD: ${DB_PASSWORD}
        mariadb:  
                container_name: ${DB_HOST}
                build: ./mariadb
                image: ${DB_HOST}
                volumes:
                        - mariadb:/var/lib/mysql
                networks:
                        - ${NETWORK}
                ports:
                    - "5121:3306"
                restart: always
                environment:
                        DB_NAME: ${DB_NAME}
                        DB_USER: ${DB_USER}
                        DB_PASSWORD: ${DB_PASSWORD}



volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/${USERNAME}/data/wordpress
                        o: bind
                        type: none
        mariadb:
                name: ${DB_HOST}
                driver: local
                driver_opts:
                        device: /home/${USERNAME}/data/mariadb
                        o: bind
                        type: none
